export default {
  LOGIN: 'login',
  LOGOUT: 'logout',
  UPDATE_CURRENT_NOTES: 'update_current_notes',
  UPDATE_CURRENT_NOTE: 'update_current_note',
  UPDATE_CURRENT_NOTE_RESOURCE: 'update_current_note_resource',
  INIT: 'init',
  SAVE_TO_LOCAL_STORE_SYNC: 'save_to_local_store_sync',
  UPDATE_ALL_CATEGORIES: 'update_all_categories',
  UPDATE_CATEGORIES_POS: 'update_categoies_pos',
  UPDATE_CURRENT_CATEGORY: 'update_current_category',
  UPDATE_CURRENT_NOTE_LOADING_STATE: 'update_current_note_loading_state',
  UPDATE_CURRENT_NOTES_LOADING_STATE: 'update_current_notes_loading_state',
  CLEAR_CURRENT_NOTE: 'clear_current_note',
  UPDATE_CONTENTS_LIST: 'update_contents_list',
  UPDATE_NOTE_STATE: 'update_note_state',
  UPDATE_ALL_TAGS: 'update_all_tags',
  UPDATE_TAG_NOTES_COUNT: 'update_tag_notes_count',
  UPDATE_CURRENT_NOTE_TAGS: 'update_current_note_tags',
  SET_CALENDAR_NOTE_DATES: 'set_calendar_note_dates',
  SET_OFFLINE_CATEGORIES: 'set_offline_categories',
  SET_OFFLINE_NOTES: 'set_offline_notes',
  SET_OFFLINE_CURRENT_CATEGORY: 'set_offline_current_category',
  UPDATE_OFFLINE_CATEGORIES: 'update_offline_categories',
  ADD_OFFLINE_CATEGORY: 'add_offline_category'
}
